- name: Get UID and GID of a user
  hosts: node
  gather_facts: false
  vars:
    my_user: gbnode
  tasks:

    - name: Query user info from /etc/passwd
      ansible.builtin.getent:
        database: passwd
        key: "{{ my_user }}"
      register: user_info

    - name: Show UID and GID
      debug:
        msg: "{{ user_info.ansible_facts.getent_passwd[my_user][1] }}"